# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Production Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    types:
    - closed
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: Set up Go
    #   uses: actions/setup-go@v3
    #   with:
    #     go-version: 1.20

    # - name: Build
    #   run: go build -o main

    # - name: Test
    #   run: go test -v ./...
    - name: Deploying
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd /var/www/grese-client
          sudo git checkout main 
          sudo git pull --rebase
          sudo rm -rf ./node_modules
          sudo npm ci --force
          sudo npm run build
          # pm2 reload grese-client --update-env
          pm2 restart grese-client
